baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "m10c"

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

  [[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/vaga"

  [params.style]
  primaryColor = "#77a6ee"
