#baseURL = 'https://jasonwhatson.com/'
#baseURL = 'http://localhost:3333'
baseURL = "https://jasonwhatson.com"
languageCode = 'en-us'
title = 'My thoughts'
theme = "m10c"
publishDir = "docs"


[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
[[menu.main]]
  weight = 1
  identifier = "cv"
  name = "CV / Resume"
  url = "http://localhost:1313/files/Jason-Whatson-senior-fullstack-engineer-ai-ml-aws-data-cv-resume.pdf" #http://localhost:1313 / https://jasonwhatson.com

  [params.style]
  primaryColor = "#77a6ee"

[params]
  author = "Jase Whatson"
  description = "Documenting my journey as a developer into AI, machine learning, web3, blockchain, finance, cryptographic consensus & related topics. DYOR"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/jasewhatson"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/jasewhatson"
  [[params.social]]
    icon = "file-text"
    name = "CV / Résumé"
    url = "/files/Jason-Whatson-senior-fullstack-engineer-ai-ml-aws-data-cv-resume.pdf"

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    noClasses = true # Use inline styles. Set to true if using CSS classes for themes.
    style = "monokai" # Replace "monokai" with your preferred style.
    lineNos = true    # Enable line numbers.
