baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My thoughts'
theme = "m10c"

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

  [params.style]
  primaryColor = "#77a6ee"

[params]
  author = "Jase"
  description = "The site description"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/gohugoio"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/gohugoio"
