#baseURL = 'https://jasonwhatson.com/'
#baseURL = 'http://localhost:3333'
baseURL = "https://jasewhatson.github.io/jasonwhatson.com/"
languageCode = 'en-us'
title = 'My thoughts'
theme = "m10c"
publishDir = "docs"


[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

  [params.style]
  primaryColor = "#77a6ee"

[params]
  author = "Jase Whatson"
  description = "Documenting my journey as a developer into web3, blockchain, finance, cryptographic consensus & related topics. DYOR"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/jasewhatson"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/jasewhatson"

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    noClasses = true # Use inline styles. Set to true if using CSS classes for themes.
    style = "monokai" # Replace "monokai" with your preferred style.
    lineNos = true    # Enable line numbers.
